### PR TITLE
fix: allow devs from other os than macos to run

### PR DESCRIPTION
**Pull request by BrunoGeorgevich**
This modification enables developers using operating systems other than macOS to run the application without issues. Without these configurations, developers on other operating systems would encounter an error, such as:
```
$ cross-env DEBUG=1 electron-forge start
✔ Checking your system
❯ Locating application
✔ Locating application
❯ Loading configuration
Failed to load: B:\Documentos\Workspaces\witsy\forge.config.ts
✖ Loading configuration [FAILED:
1. ⨯ Unable to compile TypeScript:
forge.config.ts:123:31 - error TS2345: Argument of type '{ icon: string; background: string; additionalDMGOptions: { window: { size: { width: number; height: number; }; position: { x: number; y: number; }; }; }; }' is not assignable to parameter of type 'MakerDMGConfig | ((arch: string) => MakerDMGConfig)'.
  Type '{ icon: string; background: string; additionalDMGOptions: { window: { size: { width: number; height: number; }; position: { x: number; y: number; }; }; }; }' is not assignable to type 'MakerDMGConfig'.
    Property 'appPath' is missing in type '{ icon: string; background: string; additionalDMGOptions: { window: { size: { width: number; height: number; }; position: { x: number; y: number; }; }; }; }' but required in type 'Omit<ElectronInstallerDMGOptions, "name">'.

123     /* darwin */ new MakerDMG(dmgOptions, ['darwin']), new MakerPKG({ identity: process.env.IDENTITY_MAS_PKG, }, ['mas']),
                                  ~~~~~~~~~~

  node_modules/electron-installer-dmg/dist/index.d.ts:6:5
    6     appPath: string;
          ~~~~~~~
    'appPath' is declared here.

2. Unknown file extension ".ts" for B:\Documentos\Workspaces\witsy\forge.config.ts]

An unhandled rejection has occurred inside Forge:
TSError:
1. ⨯ Unable to compile TypeScript:
forge.config.ts:123:31 - error TS2345: Argument of type '{ icon: string; background: string; additionalDMGOptions: { window: { size: { width: number; height: number; }; position: { x: number; y: number; }; }; }; }' is not assignable to parameter of type 'MakerDMGConfig | ((arch: string) => MakerDMGConfig)'.
  Type '{ icon: string; background: string; additionalDMGOptions: { window: { size: { width: number; height: number; }; position: { x: number; y: number; }; }; }; }' is not assignable to type 'MakerDMGConfig'.
    Property 'appPath' is missing in type '{ icon: string; background: string; additionalDMGOptions: { window: { size: { width: number; height: number; }; position: { x: number; y: number; }; }; }; }' but required in type 'Omit<ElectronInstallerDMGOptions, "name">'.

123     /* darwin */ new MakerDMG(dmgOptions, ['darwin']), new MakerPKG({ identity: process.env.IDENTITY_MAS_PKG, }, ['mas']),
                                  ~~~~~~~~~~

  node_modules/electron-installer-dmg/dist/index.d.ts:6:5
    6     appPath: string;
          ~~~~~~~
    'appPath' is declared here.

2. Unknown file extension ".ts" for B:\Documentos\Workspaces\witsy\forge.config.ts
at createTSError (B:\Documentos\Workspaces\witsy\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (B:\Documentos\Workspaces\witsy\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (B:\Documentos\Workspaces\witsy\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (B:\Documentos\Workspaces\witsy\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (B:\Documentos\Workspaces\witsy\node_modules\ts-node\src\index.ts:1617:30)
    at node:internal/modules/cjs/loader:1708:10
    at Object.require.extensions.<computed> [as .ts] (B:\Documentos\Workspaces\witsy\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:138:16)
    at dynamicImportMaybe (B:\Documentos\Workspaces\witsy\node_modules\@electron-forge\core\helper\dynamic-import.js:14:12)
    at exports.default (B:\Documentos\Workspaces\witsy\node_modules\@electron-forge\core\src\util\forge-config.ts:143:47)
    at async B:\Documentos\Workspaces\witsy\node_modules\@electron-forge\core\src\api\start.ts:77:31
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### CODE REVIEW

**Comment by nbonamy** [comment]
Hi. I am surprised this is needed as I am able to run Witsy from VSCode on Windows 11 without needing the `isDarwin` change. What is your dev environment exactly?
- node version
- ...

**Comment by BrunoGeorgevich** [comment]
My current node version is the LTS: v22.12.0. The OS is Windows 11.

**Comment by BrunoGeorgevich** [comment]
I've submitted a new pull request with the complete feature added to the Scratchpad. It appears we are using different linters, because my development environment is automatically changing the quotes and indentations. Which linter are you using? This kind of situation obscures the changes I've made and makes it harder to review.

**Comment by nbonamy** [comment]
Hi. Sorry but:

1. Please not put two different changes in the same PR. Create two different so they can be reviewed and merged independently.
2. Please preserve the current coding style / indentation / ... As of now both PR basically change every single line of the files they touch making it very difficult to identify what was changed and therefore what needs to be reviewed.

Thanks

**Comment by BrunoGeorgevich** [comment]
Unfortunately, you now need to reject the second commit before submitting a new pull request. I should have created a new branch to tackle each issue.

Sorry about that.

Regarding to the coding style, do you use a specific linter?

**Review by nbonamy — CHANGES_REQUESTED** [review]
As discussed please create a different PR

**Review by nbonamy — CHANGES_REQUESTED** [review]
Please make sure only the changes are submitted without modifying unrelated lines

**Comment by nbonamy** [comment]
Linting is configured: just run `npm run lint`. Only error reported is within a dependency. Did not have time to handle that.

But code formatting is different than listing: just do not use any tool that reformats everything. Thanks!

**Comment by nbonamy** [comment]
BTW the error you have about `appPath` missing is happening if you are using a different version of electron-forge than the one specified in `package.json` (7.4.0).

**Pull request closed without merging**
